pipeline:
  prepare:
    image: phpdrone/composer:php72-latest
    commands:
      - composer install --ansi

  phpcs:
    group: test
    image: phpdrone/composer:php72-latest
    commands:
      - ./vendor/bin/phpcs

  phpdoc:
    group: test
    image: phpdrone/phpdoc

  deploy-docs:
    image: fpfis/drone-plugin-git-deploy
    source: doc
    target_repo: git@github.com:phpdrone/drone-plugin-sdk.git
    target_folder: gh-pages
    clean: true
    secrets: [ deploy_key ]
    message: "Published ${DRONE_COMMIT_SHA} [CI SKIP]"
    target_branch: gh-pages
    excludes:
      - CNAME
      - phpdoc-cache-*